### ISSUE TITLE
The role of z in the netG

### ISSUE THREAD

**Issue by ywxjm** [Retinal-Research/CUNSB-RFIE#2]
Thanks for your excellent work.
In your code, models/sb_model.py line 232 and line 238
z is a Gaussian noise, Can you help explain what the input z does for netG?
Moreover, I notice that the input of netG is (xti, ti)

**Comment by Aran-Dong** [comment]
Hi, thanks for your interest. Here z typically works as the forward Gaussian noise used to iteratively generate the image for randomly selected step t_i in iterative forward training process, which is used to simulate the Schrodinger Bridge Coupling between t_i and t_1. Since the model netG is trained on every ti, it takes the input x_ti, which is the images for that specific step, and ti is the step information. Further information can be checked in our paper. Hope it's helpful.
